class CommonConstants:
    WORKON_HOME = 'WORKON_HOME'
    REQUEST_REACH_LIMIT_ERROR_CODE = 17
    ERROR_MSG = 'error_msg'
    ERROR_CODE = 'error_code'
    WORDS_RESULT = 'words_result'
    WORDS = 'words'
    PW = 'PDF_CONVERT_PASSWORD'
    OCR_CLIENT_ID = 'gAAAAABf5L7Ssk7T_81Vw3wAOd2C2DGHtllVGrqJ0TL6a3-HkN4AN5oIWtXK5Ri0R4ywp59nt13TWMa7aHwhhpgLwFm4JG1ut0VcRixR0CGkbMa2Z_lzI7M='
    OCR_CLIENT_SECRET = 'gAAAAABf5L7omssOIiQLNkSHToNOkFP451XpyzqzJE3Hswz_xr5mq0wC4D4AokHGBPVs-Dpyfbai39er-MTqOVLPqyjq9mpOsbCke3CFEdZnuKltDD8VezwNVBdndCxJVEbMOaR6xSDh'
    OCR_AUTH_URL = 'https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials&client_id={}&client_secret={}'
    OCR_ENDPOINT = 'https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic?access_token='
    ACCESS_TOKEN = 'access_token'
    TTS_APPID = 'gAAAAABf5MJOjC-6c_rSlL4Dvxq24NGhTV8db4LJDTojgyxb59hAkC4rRIOZQt_q4H83ZVCU-ua74ZZCg3ojM7QozGa60nUhFg=='
    TTS_APIKEY = 'gAAAAABf5MJjEUZ2yRPJmEJWAFsqkyBQiY1Z3y1FEQlICvdv5OAuffZGr8eOmMaWvZdLvuNbi_ONvRpKkdJmVWLxtLF1-u5zeKbLm-6DB4rJmK6LdM0cFLtACkL7KhC5h7ms0lXo1J-F'
    TTS_APISECRET = 'gAAAAABf5MJ5by-CSB9g0yqo9jD3WfloJNYPOORDs8FNnYLGKY-Y3oAZk-xoshoyPpAJuwLAmdSfINUcNjpSEee4bjO610D2bVJad2lxSHgMPw7mQr1ssshRD-Dmuxu9-5PrvFNcBCnL'
